language: c

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2abb0e79562ccc0d19b8
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_install:
  - export SOURCE_DIR=`pwd`
  - sudo apt-get update -qq
  - sudo apt-get install -y scons git flex uuid-dev libevent-dev cmake git libzmq3-dev libgtest-dev
  - cd
  - wget https://github.com/apache/qpid-proton/archive/0.15.0.tar.gz -O proton.tgz
  - tar xvf proton.tgz
  - cd qpid-proton*
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_TESTING:BOOL=OFF -DBUILD_JAVA:BOOL=OFF
  - sudo make install
  - cd
  - git clone https://github.com/OpenMAMA/OpenMAMA.git
  - cd OpenMAMA
  - git checkout next
  - export MAMA_SOURCE=$(pwd)
  - export MAMA_INSTALL=$MAMA_SOURCE/$(ls -1 | grep "openmama_install_*")
  - export LD_LIBRARY_PATH=$MAMA_INSTALL/lib:/usr/local/lib:/usr/local/lib64:$SOURCE_DIR
  - export PATH=$(echo ~/OpenMAMA/openmama_install_*/bin):$PATH
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
  - scons product=mama middleware=qpid with_unittest=y

script:
 - cd $SOURCE_DIR
 - scons --with-mamasource=$MAMA_SOURCE --with-mamainstall=$MAMA_INSTALL --with-gtest=/usr/local
 - ./unittests
 - UnitTestMamaMsgC -m qpid -p omnmmsg -i O
 - UnitTestMamaPayloadC -m qpid -p omnmmsg -i O
